import { Button } from "../button.slint";

export component EnvironmentUpdate inherits Rectangle {
    in-out property <bool> updating-env: false;
    in property <length> root-height;
    in property <bool> wifi-status: false;

    callback update-environment();

    VerticalLayout {
        height: root-height * 0.27;
        y: root-height * 0.07;
        alignment: center;
        spacing: root-height * 0.02;

        Text {
            color: black;
            wrap: word-wrap;
            width: 100%;
            font-size: root-height * 0.027;
            font-family: "Inter";
            horizontal-alignment: center;
            vertical-alignment: center;
            text: root.updating-env ? "Please wait..." : (root.wifi-status ? "Click below to update the jailbreaking environment:" : "Please exit Jobman and turn on Wi-Fi to proceed.");
        }

        HorizontalLayout {
            alignment: center;

            Button {
                root-height: root-height;
                text: "Upgrade Environment";
                disabled: !root.wifi-status || root.updating-env;
                width: root-height * 0.5;
                clicked => {
                    root.updating-env = true;
                    root.update-environment();
                }
            }
        }

        Text {
            text: "Update periodically as you see fit. All updates are triggered manually.";
            color: #4b5563;
            wrap: word-wrap;
            width: 100%;
            font-size: root.width * 0.03;
            font-family: "Inter";
            horizontal-alignment: center;
            vertical-alignment: center;
        }
    }
}
